### ISSUE TITLE
Publish data to NPM instead of relying on request for each user

### ISSUE THREAD

**Issue by blakeembrey** [Zertz/unicode-json#6]
Publishing it once to NPM seems easier than having everyone be able to connect and download the unicode data.

**Comment by Zertz** [comment]
Yes, downloading could be part of a build step.

**Comment by zoellner** [comment]
I support this issue given that it is not always save to let postinstall scripts run. See http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

**Comment by wolfika** [comment]
Note that using this package is currently a vulnerability, according to nodesecurity.io. https://nodesecurity.io/advisories/206

**Comment by Zertz** [comment]
Fixing the `postinstall` issue requires some logistics and I'm definitely open to a PR. The vulnerability has been fixed in v2.0.0

**Comment by Zertz** [comment]
Please upgrade to [node-unicodetable](https://github.com/eversport/node-unicodetable) as it is safer, faster, versioned and fully compatible
